version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local


